### ISSUE TITLE
Add mod support

### ISSUE THREAD

**Issue by ArcticEcho** [SO-Close-Vote-Reviewers/SOCVR-Chatbot#152]
Mods currently don't [appear](http://chat.stackoverflow.com/transcript/message/29320886#29320886) to have any more access to the bot than regular users. Whereas the docs state:

> Moderators have access to all commands.

**Comment by gunr2171** [comment]
Well, that's [technically correct](https://www.youtube.com/watch?v=hou0lU8WMgo). Mods _do_ have access to _run_ all commands. The issue is that they are not in all permission groups.

So, easy way to fix this:

When a mod posts a message, after we `EnsureUserInDatabase` and before anything else (like checking if it's a command), we make sure that the user is in all permission groups.
