### ISSUE TITLE
SEDE data does not refresh when asked

### ISSUE THREAD

**Issue by gunr2171** [SO-Close-Vote-Reviewers/SOCVR-Chatbot#80]
We noticed that the ajax tag remained at the top of the list, even though when you manually went to the data query it was gone.

http://chat.stackoverflow.com/transcript/message/22565284#22565284

Rene thinks that the cache is not getting invalidated.

This happens on a "refresh tag" command or waiting 30 minutes.

**Comment by ArcticEcho** [comment]
I think I've found the problem.

```C#
if (tags == null || (DateTime.UtcNow - lastRevIdCheckTime).TotalMinutes > 30)
```
<sup>[SEDEAccessor:L82](https://github.com/SO-Close-Vote-Reviewers/SOCVR-Chatbot/blob/master/CVChatbot/CVChatbot.Bot/SEDEAccessor.cs#L82).</sup>

That's the condition for actually refreshing the data, so obviously there's no way (currently) to force cache invalidation for half an hour.

Since the invalidate method simply does,

```C#
lastRevIdCheckTime = DateTime.MinValue;
```
<sup>[SEDEAccessor:L59](https://github.com/SO-Close-Vote-Reviewers/SOCVR-Chatbot/blob/master/CVChatbot/CVChatbot.Bot/SEDEAccessor.cs#L59).</sup>
