### ISSUE TITLE
Messages with a - in them cause errors

### ISSUE THREAD

**Issue by durron597** [SO-Close-Vote-Reviewers/SOCVR-Chatbot#98]
When I write a message with a `-` in it, it seems to make the bot think there is an error. Usually this happens when replying to SmokeDetector, e.g.

    me: :25156914 fp-
    Closey: error happened! 
    Closey: 0: Could not retrieve data of message 25156914. Do you have an active internet connection?

**Comment by gunr2171** [comment]
Isn't that because a Smokey message is deleted, and the cv bot is trying to read it?

My guess at the order of operations:

1. You type `fp-`
2. Smokey deletes it's message
3. Closey picks up your `fp-` message
4. Closey tries to figure out everything about the message, including the message it was a reply to. However, because the message has been delete, it errors out.

That's my best guess. @Sam should know more.

**Comment by ArcticEcho** [comment]
I have a feeling this was caused by a recent update to CE.Net. (A few weeks a ago I introduced support for the deleted message event, which has probably screwed things up.)
